### ISSUE TITLE
Lab data missing. 

### ISSUE THREAD

**Issue by saching13** [MIT-SPARK/VNAV-lab-data#1]
Hello @jingnanshi ,
I was working on lab5 Deliverable 6 [here](https://vnav.mit.edu/labs/lab5/exercises.html#-deliverable-6---comparing-feature-matching-algorithms-on-real-data-20-pts--optional-10-pts) and found that the data links to this repo but hasn't been uploaded yet. 
It would be really helpful if you could share it. 

Thanks,
Sachin

**Comment by jingnanshi** [comment]
Hi @saching13, the data can be found in the link in the README of https://github.com/MIT-SPARK/VNAV-lab-data. Thanks.

**Comment by saching13** [comment]
Thanks. My bad. Maybe we can update the link in the web too. It would help others too.
